"""
Enrich university knowledge base with mascots, websites, coach data, and other missing fields.
Run: cd /app/backend && python3 scripts/enrich_universities.py
"""
import asyncio
import os
import sys

# Set env vars from .env file
with open(os.path.join(os.path.dirname(__file__), '..', '.env')) as f:
    for line in f:
        line = line.strip()
        if '=' in line and not line.startswith('#'):
            k, v = line.split('=', 1)
            os.environ[k] = v.strip('"').strip("'")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from database import db


# ── Mascot data for ~1000+ NCAA volleyball programs ──
MASCOTS = {
    "Abilene Christian University": "Wildcats",
    "Academy of Art University": "Urban Knights",
    "Adams State University": "Grizzlies",
    "Adelphi University": "Panthers",
    "Adrian College": "Bulldogs",
    "Agnes Scott College": "Scotties",
    "Alabama A&M University": "Bulldogs",
    "Alabama State University": "Hornets",
    "Albany State University": "Golden Rams",
    "Albertus Magnus College": "Falcons",
    "Albion College": "Britons",
    "Albright College": "Lions",
    "Alcorn State University": "Lady Braves",
    "Alfred State College": "Pioneers",
    "Alfred University": "Saxons",
    "Allegheny College": "Gators",
    "Allen University": "Yellow Jackets",
    "Alma College": "Scots",
    "Alvernia University": "Golden Wolves",
    "Alverno College": "Inferno",
    "American International College": "Yellow Jackets",
    "American University": "Eagles",
    "Amherst College": "Mammoths",
    "Anderson University (IN)": "Ravens",
    "Anderson University (SC)": "Trojans",
    "Angelo State University": "Rambelles",
    "Anna Maria College": "AmCats",
    "Appalachian State University": "Mountaineers",
    "Arcadia University": "Knights",
    "Arizona Christian University": "Firestorm",
    "Arizona State University": "Sun Devils",
    "Arkansas State University": "Red Wolves",
    "Arkansas Tech University": "Golden Suns",
    "Auburn University": "Tigers",
    "Auburn University at Montgomery": "Warhawks",
    "Augustana College": "Vikings",
    "Augustana University": "Vikings",
    "Aurora University": "Spartans",
    "Austin College": "Kangaroos",
    "Austin Peay State University": "Governors",
    "Averett University": "Cougars",
    "Azusa Pacific University": "Cougars",
    "Babson College": "Beavers",
    "Baker University": "Wildcats",
    "Baldwin Wallace University": "Yellow Jackets",
    "Ball State University": "Cardinals",
    "Barton College": "Bulldogs",
    "Bates College": "Bobcats",
    "Baylor University": "Bears",
    "Bellarmine University": "Knights",
    "Belmont Abbey College": "Crusaders",
    "Belmont University": "Bruins",
    "Beloit College": "Buccaneers",
    "Bemidji State University": "Beavers",
    "Benedict College": "Tigers",
    "Benedictine College": "Ravens",
    "Benedictine University": "Eagles",
    "Bentley University": "Falcons",
    "Berry College": "Vikings",
    "Bethany College (KS)": "Swedes",
    "Bethany College (WV)": "Bison",
    "Bethany Lutheran College": "Vikings",
    "Bethel University (IN)": "Pilots",
    "Bethel University (MN)": "Royals",
    "Bethune-Cookman University": "Wildcats",
    "Binghamton University": "Bearcats",
    "Biola University": "Eagles",
    "Birmingham-Southern College": "Panthers",
    "Black Hills State University": "Yellow Jackets",
    "Bloomfield College": "Bears",
    "Bloomsburg University": "Huskies",
    "Bluefield State College": "Big Blues",
    "Boise State University": "Broncos",
    "Boston College": "Eagles",
    "Boston University": "Terriers",
    "Bowdoin College": "Polar Bears",
    "Bowie State University": "Bulldogs",
    "Bowling Green State University": "Falcons",
    "Bradley University": "Braves",
    "Brandeis University": "Judges",
    "Bridgewater College": "Eagles",
    "Bridgewater State University": "Bears",
    "Brigham Young University": "Cougars",
    "Brown University": "Bears",
    "Bryant University": "Bulldogs",
    "Bryn Mawr College": "Owls",
    "Bucknell University": "Bison",
    "Buffalo State College": "Bengals",
    "Butler University": "Bulldogs",
    "Cabrini University": "Cavaliers",
    "Cal Poly": "Mustangs",
    "Cal Poly Pomona": "Broncos",
    "Cal State Bakersfield": "Roadrunners",
    "Cal State Dominguez Hills": "Toros",
    "Cal State East Bay": "Pioneers",
    "Cal State Fullerton": "Titans",
    "Cal State LA": "Golden Eagles",
    "Cal State Monterey Bay": "Otters",
    "Cal State Northridge": "Matadors",
    "Cal State San Bernardino": "Coyotes",
    "Cal State San Marcos": "Cougars",
    "Cal State Stanislaus": "Warriors",
    "California Baptist University": "Lancers",
    "California Lutheran University": "Regals",
    "Calvin University": "Knights",
    "Cameron University": "Aggies",
    "Campbell University": "Fighting Camels",
    "Canisius College": "Golden Griffins",
    "Capital University": "Crusaders",
    "Carleton College": "Knights",
    "Carnegie Mellon University": "Tartans",
    "Carroll College": "Fighting Saints",
    "Carroll University": "Pioneers",
    "Carson-Newman University": "Eagles",
    "Carthage College": "Firebirds",
    "Case Western Reserve University": "Spartans",
    "Castleton University": "Spartans",
    "Catawba College": "Indians",
    "Catholic University": "Cardinals",
    "Cedarville University": "Yellow Jackets",
    "Central Arkansas": "Sugar Bears",
    "Central College": "Dutch",
    "Central Connecticut State University": "Blue Devils",
    "Central Methodist University": "Eagles",
    "Central Michigan University": "Chippewas",
    "Central Missouri": "Jennies",
    "Central Washington University": "Wildcats",
    "Centre College": "Colonels",
    "Chadron State College": "Eagles",
    "Chapman University": "Panthers",
    "Charleston Southern University": "Buccaneers",
    "Chatham University": "Cougars",
    "Chestnut Hill College": "Griffins",
    "Chicago State University": "Cougars",
    "Chowan University": "Hawks",
    "Christian Brothers University": "Buccaneers",
    "Christopher Newport University": "Captains",
    "Cincinnati": "Bearcats",
    "Claremont-Mudd-Scripps": "Stags/Athenas",
    "Clark University": "Cougars",
    "Clarkson University": "Golden Knights",
    "Clayton State University": "Lakers",
    "Clemson University": "Tigers",
    "Cleveland State University": "Vikings",
    "Coastal Carolina University": "Chanticleers",
    "Coe College": "Kohawks",
    "Coker University": "Cobras",
    "Colby College": "Mules",
    "Colgate University": "Raiders",
    "College of Charleston": "Cougars",
    "College of Saint Benedict": "Blazers",
    "College of Wooster": "Fighting Scots",
    "Colorado Christian University": "Cougars",
    "Colorado College": "Tigers",
    "Colorado Mesa University": "Mavericks",
    "Colorado School of Mines": "Orediggers",
    "Colorado State University": "Rams",
    "Colorado State University-Pueblo": "ThunderWolves",
    "Columbia University": "Lions",
    "Columbus State University": "Cougars",
    "Concordia College (MN)": "Cobbers",
    "Concordia University (CA)": "Eagles",
    "Concordia University (NE)": "Bulldogs",
    "Concordia University Chicago": "Cougars",
    "Concordia University Irvine": "Eagles",
    "Concordia University Wisconsin": "Falcons",
    "Connecticut College": "Camels",
    "Converse University": "Valkyries",
    "Coppin State University": "Eagles",
    "Cornell College": "Rams",
    "Cornell University": "Big Red",
    "Cornerstone University": "Golden Eagles",
    "Covenant College": "Scots",
    "Creighton University": "Bluejays",
    "Crown College": "Storm",
    "Culver-Stockton College": "Wildcats",
    "Cumberland University": "Phoenix",
    "Curry College": "Colonels",
    "Daemen University": "Wildcats",
    "Dakota State University": "Trojans",
    "Dakota Wesleyan University": "Tigers",
    "Dallas Baptist University": "Patriots",
    "Dartmouth College": "Big Green",
    "Davidson College": "Wildcats",
    "Dayton": "Flyers",
    "DePaul University": "Blue Demons",
    "DePauw University": "Tigers",
    "Delaware State University": "Hornets",
    "Delta State University": "Statesmen",
    "Denison University": "Big Red",
    "DeSales University": "Bulldogs",
    "Dickinson College": "Red Devils",
    "Dillard University": "Bleu Devils",
    "Dominican University": "Stars",
    "Dominican University of California": "Penguins",
    "Dordt University": "Defenders",
    "Drake University": "Bulldogs",
    "Drexel University": "Dragons",
    "Drury University": "Panthers",
    "Duke University": "Blue Devils",
    "Duquesne University": "Dukes",
    "Earlham College": "Quakers",
    "East Carolina University": "Pirates",
    "East Central University": "Tigers",
    "East Stroudsburg University": "Warriors",
    "East Tennessee State University": "Buccaneers",
    "East Texas Baptist University": "Tigers",
    "Eastern Connecticut State University": "Warriors",
    "Eastern Illinois University": "Panthers",
    "Eastern Kentucky University": "Colonels",
    "Eastern Mennonite University": "Royals",
    "Eastern Michigan University": "Eagles",
    "Eastern New Mexico University": "Greyhounds",
    "Eastern Oregon University": "Mountaineers",
    "Eastern University": "Eagles",
    "Eastern Washington University": "Eagles",
    "Eckerd College": "Tritons",
    "Edinboro University": "Fighting Scots",
    "Elizabethtown College": "Blue Jays",
    "Elmhurst University": "Bluejays",
    "Elmira College": "Soaring Eagles",
    "Elon University": "Phoenix",
    "Embry-Riddle Aeronautical University": "Eagles",
    "Emerson College": "Lions",
    "Emmanuel College": "Saints",
    "Emory & Henry College": "Wasps",
    "Emory University": "Eagles",
    "Emporia State University": "Hornets",
    "Endicott College": "Gulls",
    "Erskine College": "Flying Fleet",
    "Evangel University": "Crusaders",
    "Evansville": "Purple Aces",
    "Fairfield University": "Stags",
    "Fairleigh Dickinson University": "Knights",
    "Fairmont State University": "Falcons",
    "Farmingdale State College": "Rams",
    "Fayetteville State University": "Broncos",
    "Felician University": "Golden Falcons",
    "Ferris State University": "Bulldogs",
    "Ferrum College": "Panthers",
    "Flagler College": "Saints",
    "Florida A&M University": "Rattlers",
    "Florida Atlantic University": "Owls",
    "Florida Gulf Coast University": "Eagles",
    "Florida Institute of Technology": "Panthers",
    "Florida International University": "Panthers",
    "Florida Memorial University": "Lions",
    "Florida Southern College": "Moccasins",
    "Florida State University": "Seminoles",
    "Fontbonne University": "Griffins",
    "Fordham University": "Rams",
    "Fort Hays State University": "Tigers",
    "Fort Lewis College": "Skyhawks",
    "Fort Valley State University": "Wildcats",
    "Framingham State University": "Rams",
    "Francis Marion University": "Patriots",
    "Franklin & Marshall College": "Diplomats",
    "Franklin College": "Grizzlies",
    "Franklin Pierce University": "Ravens",
    "Freed-Hardeman University": "Lions",
    "Fresno Pacific University": "Sunbirds",
    "Fresno State": "Bulldogs",
    "Frostburg State University": "Bobcats",
    "Furman University": "Paladins",
    "Gallaudet University": "Bison",
    "Gannon University": "Golden Knights",
    "Gardner-Webb University": "Runnin' Bulldogs",
    "Geneva College": "Golden Tornadoes",
    "George Fox University": "Bruins",
    "George Mason University": "Patriots",
    "George Washington University": "Revolutionaries",
    "Georgetown College": "Tigers",
    "Georgetown University": "Hoyas",
    "Georgia College": "Bobcats",
    "Georgia Institute of Technology": "Yellow Jackets",
    "Georgia Southern University": "Eagles",
    "Georgia Southwestern State University": "Hurricanes",
    "Georgia State University": "Panthers",
    "Gettysburg College": "Bullets",
    "Gonzaga University": "Bulldogs",
    "Gordon College": "Fighting Scots",
    "Goshen College": "Maple Leafs",
    "Goucher College": "Gophers",
    "Grace College": "Lancers",
    "Graceland University": "Yellowjackets",
    "Grand Canyon University": "Antelopes",
    "Grand Valley State University": "Lakers",
    "Grand View University": "Vikings",
    "Green Mountain College": "Eagles",
    "Greensboro College": "Pride",
    "Greenville University": "Panthers",
    "Grinnell College": "Pioneers",
    "Grove City College": "Wolverines",
    "Guilford College": "Quakers",
    "Gustavus Adolphus College": "Gusties",
    "Gwynedd Mercy University": "Griffins",
    "Hamilton College": "Continentals",
    "Hamline University": "Pipers",
    "Hampden-Sydney College": "Tigers",
    "Hampton University": "Pirates",
    "Hannibal-LaGrange University": "Trojans",
    "Hanover College": "Panthers",
    "Harding University": "Lady Bisons",
    "Hardin-Simmons University": "Cowgirls",
    "Hartford": "Hawks",
    "Hartwick College": "Hawks",
    "Harvard University": "Crimson",
    "Harvey Mudd College": "Stags/Athenas",
    "Hastings College": "Broncos",
    "Haverford College": "Fords",
    "Hawaii Pacific University": "Sharks",
    "Henderson State University": "Reddies",
    "Hendrix College": "Warriors",
    "High Point University": "Panthers",
    "Hilbert College": "Hawks",
    "Hillsdale College": "Chargers",
    "Hiram College": "Terriers",
    "Hobart and William Smith Colleges": "Herons",
    "Hofstra University": "Pride",
    "Hollins University": "Green",
    "Holy Cross": "Crusaders",
    "Hood College": "Blazers",
    "Hope College": "Flying Dutch",
    "Houghton University": "Highlanders",
    "Houston Baptist University": "Huskies",
    "Howard Payne University": "Yellow Jackets",
    "Howard University": "Bison",
    "Humboldt State University": "Lumberjacks",
    "Huntingdon College": "Hawks",
    "Huntington University": "Foresters",
    "Husson University": "Eagles",
    "Huston-Tillotson University": "Rams",
    "Idaho State University": "Bengals",
    "Illinois College": "Blueboys/Lady Blues",
    "Illinois Institute of Technology": "Scarlet Hawks",
    "Illinois State University": "Redbirds",
    "Illinois Wesleyan University": "Titans",
    "Immaculata University": "Mighty Macs",
    "Indiana State University": "Sycamores",
    "Indiana Tech": "Warriors",
    "Indiana University": "Hoosiers",
    "Indiana University of Pennsylvania": "Crimson Hawks",
    "Indiana Wesleyan University": "Wildcats",
    "Iona University": "Gaels",
    "Iowa State University": "Cyclones",
    "Iowa Wesleyan University": "Tigers",
    "Ithaca College": "Bombers",
    "Jackson State University": "Tigers",
    "Jacksonville State University": "Gamecocks",
    "Jacksonville University": "Dolphins",
    "James Madison University": "Dukes",
    "Jamestown University": "Jimmies",
    "John Carroll University": "Blue Streaks",
    "Johns Hopkins University": "Blue Jays",
    "Johnson & Wales University": "Wildcats",
    "Johnson C. Smith University": "Golden Bulls",
    "Juniata College": "Eagles",
    "Kalamazoo College": "Hornets",
    "Kansas State University": "Wildcats",
    "Kansas Wesleyan University": "Coyotes",
    "Kean University": "Cougars",
    "Keene State College": "Owls",
    "Kennesaw State University": "Owls",
    "Kent State University": "Golden Flashes",
    "Kentucky State University": "Thorobreds",
    "Kentucky Wesleyan College": "Panthers",
    "Kenyon College": "Ladies",
    "Keuka College": "Wolves",
    "King University": "Tornado",
    "King's College": "Monarchs",
    "Knox College": "Prairie Fire",
    "Kutztown University": "Golden Bears",
    "La Salle University": "Explorers",
    "La Sierra University": "Golden Eagles",
    "Lafayette College": "Leopards",
    "Lake Erie College": "Storm",
    "Lake Forest College": "Foresters",
    "Lake Superior State University": "Lakers",
    "Lamar University": "Cardinals",
    "Lander University": "Bearcats",
    "Lane College": "Dragons",
    "Lawrence University": "Vikings",
    "Le Moyne College": "Dolphins",
    "Lebanon Valley College": "Flying Dutchmen",
    "Lee University": "Flames",
    "Lehigh University": "Mountain Hawks",
    "LeMoyne-Owen College": "Magicians",
    "Lenoir-Rhyne University": "Bears",
    "LeTourneau University": "YellowJackets",
    "Lewis & Clark College": "Pioneers",
    "Lewis University": "Flyers",
    "Liberty University": "Flames",
    "Limestone University": "Saints",
    "Lincoln Memorial University": "Railsplitters",
    "Lincoln University (MO)": "Blue Tigers",
    "Lincoln University (PA)": "Lions",
    "Lindenwood University": "Lions",
    "Lindsey Wilson College": "Blue Raiders",
    "Linfield University": "Wildcats",
    "Lipscomb University": "Bisons",
    "Lock Haven University": "Bald Eagles",
    "Long Island University": "Sharks",
    "Longwood University": "Lancers",
    "Loras College": "Duhawks",
    "Louisiana State University": "Tigers",
    "Louisiana Tech University": "Lady Techsters",
    "Louisville": "Cardinals",
    "Loyola Marymount University": "Lions",
    "Loyola University Chicago": "Ramblers",
    "Loyola University Maryland": "Greyhounds",
    "Lubbock Christian University": "Lady Chaps",
    "Luther College": "Norse",
    "Lycoming College": "Warriors",
    "Lynn University": "Fighting Knights",
    "Macalester College": "Scots",
    "Malone University": "Pioneers",
    "Manchester University": "Spartans",
    "Manhattan College": "Jaspers",
    "Manhattanville College": "Valiants",
    "Mansfield University": "Mountaineers",
    "Marian University": "Knights",
    "Marist College": "Red Foxes",
    "Marquette University": "Golden Eagles",
    "Mars Hill University": "Lions",
    "Marshall University": "Thundering Herd",
    "Mary Baldwin University": "Fighting Squirrels",
    "Marymount University": "Saints",
    "Maryville College": "Scots",
    "Maryville University": "Saints",
    "Massachusetts Institute of Technology": "Engineers",
    "McKendree University": "Bearcats",
    "McMurry University": "War Hawks",
    "McNeese State University": "Cowgirls",
    "McPherson College": "Bulldogs",
    "Mercer University": "Bears",
    "Mercy College": "Mavericks",
    "Mercyhurst University": "Lakers",
    "Meredith College": "Avenging Angels",
    "Merrimack College": "Warriors",
    "Messiah University": "Falcons",
    "Methodist University": "Monarchs",
    "Metropolitan State University of Denver": "Roadrunners",
    "Miami University": "RedHawks",
    "Michigan State University": "Spartans",
    "Michigan Technological University": "Huskies",
    "MidAmerica Nazarene University": "Pioneers",
    "Middle Tennessee State University": "Blue Raiders",
    "Middlebury College": "Panthers",
    "Midland University": "Warriors",
    "Midwestern State University": "Mustangs",
    "Millersville University": "Marauders",
    "Milligan University": "Buffaloes",
    "Millikin University": "Big Blue",
    "Mills College": "Cyclones",
    "Millsaps College": "Majors",
    "Milwaukee School of Engineering": "Raiders",
    "Minnesota State University, Mankato": "Mavericks",
    "Minnesota State University Moorhead": "Dragons",
    "Minot State University": "Beavers",
    "Misericordia University": "Cougars",
    "Mississippi College": "Choctaws",
    "Mississippi State University": "Bulldogs",
    "Mississippi Valley State University": "Devilettes",
    "Missouri Baptist University": "Spartans",
    "Missouri Southern State University": "Lions",
    "Missouri State University": "Bears",
    "Missouri University of Science and Technology": "Miners",
    "Missouri Valley College": "Vikings",
    "Missouri Western State University": "Griffons",
    "MIT": "Engineers",
    "Molloy University": "Lions",
    "Monmouth College": "Fighting Scots",
    "Monmouth University": "Hawks",
    "Montana State University": "Bobcats",
    "Montana State University Billings": "Yellowjackets",
    "Montana Tech": "Orediggers",
    "Montclair State University": "Red Hawks",
    "Moravian University": "Greyhounds",
    "Morehead State University": "Eagles",
    "Morehouse College": "Maroon Tigers",
    "Morgan State University": "Bears",
    "Morningside University": "Mustangs",
    "Mount Holyoke College": "Lyons",
    "Mount Mercy University": "Mustangs",
    "Mount Olive University": "Trojans",
    "Mount Saint Mary's University": "Mountaineers",
    "Mount St. Mary's University": "Mountaineers",
    "Mount Union": "Purple Raiders",
    "Muhlenberg College": "Mules",
    "Murray State University": "Racers",
    "Muskingum University": "Fighting Muskies",
    "Navy": "Midshipmen",
    "Nebraska Wesleyan University": "Prairie Wolves",
    "New Jersey City University": "Gothic Knights",
    "New Mexico Highlands University": "Cowgirls",
    "New Mexico State University": "Aggies",
    "New York University": "Violets",
    "Newberry College": "Wolves",
    "Newman University": "Jets",
    "Niagara University": "Purple Eagles",
    "Nicholls State University": "Colonels",
    "Nichols College": "Bison",
    "Norfolk State University": "Spartans",
    "North Carolina A&T State University": "Aggies",
    "North Carolina Central University": "Eagles",
    "North Carolina State University": "Wolfpack",
    "North Central College": "Cardinals",
    "North Dakota State University": "Bison",
    "North Greenville University": "Crusaders",
    "North Park University": "Vikings",
    "Northeastern State University": "RiverHawks",
    "Northeastern University": "Huskies",
    "Northern Arizona University": "Lumberjacks",
    "Northern Colorado": "Bears",
    "Northern Illinois University": "Huskies",
    "Northern Iowa": "Panthers",
    "Northern Kentucky University": "Norse",
    "Northern Michigan University": "Wildcats",
    "Northern State University": "Wolves",
    "Northwest Missouri State University": "Bearcats",
    "Northwest Nazarene University": "Nighthawks",
    "Northwestern College": "Red Raiders",
    "Northwestern State University": "Demons",
    "Northwestern University": "Wildcats",
    "Norwich University": "Cadets",
    "Notre Dame College": "Falcons",
    "Nova Southeastern University": "Sharks",
    "Nyack College": "Warriors",
    "Oakland University": "Golden Grizzlies",
    "Oberlin College": "Yeomen/Yeowomen",
    "Occidental College": "Tigers",
    "Oglethorpe University": "Stormy Petrels",
    "Ohio Dominican University": "Panthers",
    "Ohio Northern University": "Polar Bears",
    "Ohio State University": "Buckeyes",
    "Ohio University": "Bobcats",
    "Ohio Wesleyan University": "Battling Bishops",
    "Oklahoma Baptist University": "Bison",
    "Oklahoma Christian University": "Eagles",
    "Oklahoma State University": "Cowgirls",
    "Old Dominion University": "Monarchs",
    "Olivet College": "Comets",
    "Olivet Nazarene University": "Tigers",
    "Oral Roberts University": "Golden Eagles",
    "Oregon State University": "Beavers",
    "Ottawa University": "Braves",
    "Otterbein University": "Cardinals",
    "Ouachita Baptist University": "Tigers",
    "Pace University": "Setters",
    "Pacific Lutheran University": "Lutes",
    "Pacific University": "Boxers",
    "Palm Beach Atlantic University": "Sailfish",
    "Pepperdine University": "Waves",
    "Penn State University": "Nittany Lions",
    "Pennsylvania": "Quakers",
    "Pfeiffer University": "Falcons",
    "Philadelphia University": "Rams",
    "Piedmont University": "Lions",
    "Pittsburg State University": "Gorillas",
    "Pittsburgh": "Panthers",
    "Plymouth State University": "Panthers",
    "Point Loma Nazarene University": "Sea Lions",
    "Point Park University": "Pioneers",
    "Pomona-Pitzer Colleges": "Sagehens",
    "Portland State University": "Vikings",
    "Prairie View A&M University": "Panthers",
    "Presbyterian College": "Blue Hose",
    "Princeton University": "Tigers",
    "Providence College": "Friars",
    "Purdue University": "Boilermakers",
    "Purdue University Fort Wayne": "Mastodons",
    "Purdue University Northwest": "Pride",
    "Queens University of Charlotte": "Royals",
    "Quinnipiac University": "Bobcats",
    "Radford University": "Highlanders",
    "Ramapo College": "Roadrunners",
    "Randolph College": "WildCats",
    "Randolph-Macon College": "Yellow Jackets",
    "Regis University": "Rangers",
    "Rensselaer Polytechnic Institute": "Engineers",
    "Rhode Island College": "Anchormen",
    "Rhodes College": "Lynx",
    "Rice University": "Owls",
    "Rider University": "Broncs",
    "Ripon College": "Red Hawks",
    "Roanoke College": "Maroons",
    "Robert Morris University": "Colonials",
    "Roberts Wesleyan University": "Redhawks",
    "Rochester Institute of Technology": "Tigers",
    "Rockhurst University": "Hawks",
    "Rollins College": "Tars",
    "Rose-Hulman Institute of Technology": "Fightin' Engineers",
    "Rowan University": "Profs",
    "Rutgers University": "Scarlet Knights",
    "Sacred Heart University": "Pioneers",
    "Saginaw Valley State University": "Cardinals",
    "Saint Anselm College": "Hawks",
    "Saint Augustine's University": "Falcons",
    "Saint Francis University": "Red Flash",
    "Saint John Fisher University": "Cardinals",
    "Saint John's University": "Red Storm",
    "Saint Joseph's University": "Hawks",
    "Saint Leo University": "Lions",
    "Saint Louis University": "Billikens",
    "Saint Martin's University": "Saints",
    "Saint Mary's College": "Belles",
    "Saint Mary's University of Minnesota": "Cardinals",
    "Saint Michael's College": "Purple Knights",
    "Saint Peter's University": "Peacocks",
    "Saint Thomas University": "Bobcats",
    "Saint Vincent College": "Bearcats",
    "Salem University": "Tigers",
    "Salisbury University": "Sea Gulls",
    "Salve Regina University": "Seahawks",
    "Sam Houston State University": "Bearkats",
    "Samford University": "Bulldogs",
    "San Diego State University": "Aztecs",
    "San Francisco State University": "Gators",
    "San Jose State University": "Spartans",
    "Santa Clara University": "Broncos",
    "Savannah State University": "Tigers",
    "Schreiner University": "Mountaineers",
    "Seattle Pacific University": "Falcons",
    "Seattle University": "Redhawks",
    "Seton Hall University": "Pirates",
    "Seton Hill University": "Griffins",
    "Sewanee: University of the South": "Tigers",
    "Shepherd University": "Rams",
    "Shippensburg University": "Raiders",
    "Siena College": "Saints",
    "Simmons University": "Sharks",
    "Simpson College": "Storm",
    "Slippery Rock University": "The Rock",
    "Smith College": "Pioneers",
    "Sonoma State University": "Seawolves",
    "South Carolina State University": "Bulldogs",
    "South Dakota School of Mines": "Hardrockers",
    "South Dakota State University": "Jackrabbits",
    "Southeast Missouri State University": "Redhawks",
    "Southeastern Louisiana University": "Lions",
    "Southeastern Oklahoma State University": "Savage Storm",
    "Southeastern University": "Fire",
    "Southern Adventist University": "Knights",
    "Southern Arkansas University": "Muleriders",
    "Southern Connecticut State University": "Owls",
    "Southern Illinois University": "Salukis",
    "Southern Illinois University Edwardsville": "Cougars",
    "Southern Indiana": "Screaming Eagles",
    "Southern Methodist University": "Mustangs",
    "Southern Mississippi": "Golden Eagles",
    "Southern Nazarene University": "Crimson Storm",
    "Southern New Hampshire University": "Penmen",
    "Southern Oregon University": "Raiders",
    "Southern University": "Jaguars",
    "Southern Utah University": "Thunderbirds",
    "Southern Virginia University": "Knights",
    "Southern Wesleyan University": "Warriors",
    "Southwest Baptist University": "Bearcats",
    "Southwest Minnesota State University": "Mustangs",
    "Southwestern Oklahoma State University": "Bulldogs",
    "Southwestern University": "Pirates",
    "Spring Arbor University": "Cougars",
    "Spring Hill College": "Badgers",
    "Springfield College": "Pride",
    "St. Bonaventure University": "Bonnies",
    "St. Catherine University": "Wildcats",
    "St. Cloud State University": "Huskies",
    "St. Edward's University": "Hilltoppers",
    "St. John's University (MN)": "Johnnies",
    "St. Lawrence University": "Saints",
    "St. Mary's University": "Rattlers",
    "St. Norbert College": "Green Knights",
    "St. Olaf College": "Oles",
    "St. Thomas Aquinas College": "Spartans",
    "Stanford University": "Cardinal",
    "Stephen F. Austin State University": "Ladyjacks",
    "Sterling College": "Warriors",
    "Stetson University": "Hatters",
    "Stevens Institute of Technology": "Ducks",
    "Stevenson University": "Mustangs",
    "Stonehill College": "Skyhawks",
    "Stony Brook University": "Seawolves",
    "Suffolk University": "Rams",
    "Sul Ross State University": "Lobos",
    "Susquehanna University": "River Hawks",
    "Swarthmore College": "Garnet",
    "Sweet Briar College": "Vixens",
    "Syracuse University": "Orange",
    "Tabor College": "Bluejays",
    "Tarleton State University": "Texans",
    "Taylor University": "Trojans",
    "Temple University": "Owls",
    "Tennessee State University": "Tigers",
    "Tennessee Tech University": "Golden Eagles",
    "Texas A&M University": "Aggies",
    "Texas A&M University-Commerce": "Lions",
    "Texas A&M University-Corpus Christi": "Islanders",
    "Texas A&M University-Kingsville": "Javelinas",
    "Texas Christian University": "Horned Frogs",
    "Texas Lutheran University": "Bulldogs",
    "Texas Southern University": "Tigers",
    "Texas State University": "Bobcats",
    "Texas Tech University": "Red Raiders",
    "Texas Wesleyan University": "Rams",
    "Texas Woman's University": "Pioneers",
    "The Citadel": "Bulldogs",
    "Thomas More University": "Saints",
    "Tiffin University": "Dragons",
    "Toccoa Falls College": "Screaming Eagles",
    "Towson University": "Tigers",
    "Transylvania University": "Pioneers",
    "Trevecca Nazarene University": "Trojans",
    "Trinity College": "Bantams",
    "Trinity University": "Tigers",
    "Troy University": "Trojans",
    "Truman State University": "Bulldogs",
    "Tufts University": "Jumbos",
    "Tulane University": "Green Wave",
    "Tusculum University": "Pioneers",
    "Tuskegee University": "Golden Tigers",
    "UC Davis": "Aggies",
    "UC Irvine": "Anteaters",
    "UC Riverside": "Highlanders",
    "UC San Diego": "Tritons",
    "UC Santa Barbara": "Gauchos",
    "UC Santa Cruz": "Banana Slugs",
    "UCLA": "Bruins",
    "UConn": "Huskies",
    "UMass Amherst": "Minutewomen",
    "UMass Boston": "Beacons",
    "UMass Dartmouth": "Corsairs",
    "UMass Lowell": "River Hawks",
    "UMBC": "Retrievers",
    "UNC Asheville": "Bulldogs",
    "UNC Charlotte": "49ers",
    "UNC Greensboro": "Spartans",
    "UNC Pembroke": "Braves",
    "UNC Wilmington": "Seahawks",
    "Union College": "Dutchmen",
    "Union University": "Bulldogs",
    "United States Air Force Academy": "Falcons",
    "United States Military Academy": "Black Knights",
    "United States Naval Academy": "Midshipmen",
    "University at Albany": "Great Danes",
    "University at Buffalo": "Bulls",
    "University of Akron": "Zips",
    "University of Alabama": "Crimson Tide",
    "University of Alabama at Birmingham": "Blazers",
    "University of Alabama in Huntsville": "Chargers",
    "University of Alaska Anchorage": "Seawolves",
    "University of Alaska Fairbanks": "Nanooks",
    "University of Arizona": "Wildcats",
    "University of Arkansas": "Razorbacks",
    "University of Arkansas at Little Rock": "Trojans",
    "University of Arkansas at Pine Bluff": "Golden Lions",
    "University of Bridgeport": "Purple Knights",
    "University of Central Arkansas": "Sugar Bears",
    "University of Central Florida": "Knights",
    "University of Central Missouri": "Jennies",
    "University of Central Oklahoma": "Bronchos",
    "University of Charleston": "Golden Eagles",
    "University of Chicago": "Maroons",
    "University of Colorado Boulder": "Buffaloes",
    "University of Colorado Colorado Springs": "Mountain Lions",
    "University of Dallas": "Crusaders",
    "University of Dayton": "Flyers",
    "University of Delaware": "Blue Hens",
    "University of Denver": "Pioneers",
    "University of Detroit Mercy": "Titans",
    "University of Evansville": "Purple Aces",
    "University of Findlay": "Oilers",
    "University of Florida": "Gators",
    "University of Georgia": "Bulldogs",
    "University of Hartford": "Hawks",
    "University of Hawaii": "Rainbow Wahine",
    "University of Houston": "Cougars",
    "University of Idaho": "Vandals",
    "University of Illinois": "Fighting Illini",
    "University of Illinois Chicago": "Flames",
    "University of Illinois Springfield": "Prairie Stars",
    "University of Indianapolis": "Greyhounds",
    "University of Iowa": "Hawkeyes",
    "University of Kansas": "Jayhawks",
    "University of Kentucky": "Wildcats",
    "University of Louisiana at Lafayette": "Ragin' Cajuns",
    "University of Louisiana at Monroe": "Warhawks",
    "University of Louisville": "Cardinals",
    "University of Maine": "Black Bears",
    "University of Mary": "Marauders",
    "University of Mary Hardin-Baylor": "Crusaders",
    "University of Mary Washington": "Eagles",
    "University of Maryland": "Terrapins",
    "University of Maryland Eastern Shore": "Hawks",
    "University of Memphis": "Tigers",
    "University of Miami": "Hurricanes",
    "University of Michigan": "Wolverines",
    "University of Minnesota": "Golden Gophers",
    "University of Minnesota Duluth": "Bulldogs",
    "University of Mississippi": "Rebels",
    "University of Missouri": "Tigers",
    "University of Missouri-Kansas City": "Kangaroos",
    "University of Montana": "Grizzlies",
    "University of Montevallo": "Falcons",
    "University of Mount Union": "Purple Raiders",
    "University of Nebraska": "Cornhuskers",
    "University of Nebraska at Kearney": "Lopers",
    "University of Nebraska at Omaha": "Mavericks",
    "University of Nevada, Las Vegas": "Rebels",
    "University of Nevada, Reno": "Wolf Pack",
    "University of New England": "Nor'easters",
    "University of New Hampshire": "Wildcats",
    "University of New Haven": "Chargers",
    "University of New Mexico": "Lobos",
    "University of New Orleans": "Privateers",
    "University of North Alabama": "Lions",
    "University of North Carolina": "Tar Heels",
    "University of North Dakota": "Fighting Hawks",
    "University of North Florida": "Ospreys",
    "University of North Georgia": "Nighthawks",
    "University of North Texas": "Mean Green",
    "University of Northern Colorado": "Bears",
    "University of Northern Iowa": "Panthers",
    "University of Northwestern Ohio": "Racers",
    "University of Notre Dame": "Fighting Irish",
    "University of Oklahoma": "Sooners",
    "University of Oregon": "Ducks",
    "University of the Pacific": "Tigers",
    "University of Pennsylvania": "Quakers",
    "University of Pittsburgh": "Panthers",
    "University of Portland": "Pilots",
    "University of Puget Sound": "Loggers",
    "University of Redlands": "Bulldogs",
    "University of Rhode Island": "Rams",
    "University of Richmond": "Spiders",
    "University of Rochester": "Yellowjackets",
    "University of San Diego": "Toreros",
    "University of San Francisco": "Dons",
    "University of Scranton": "Royals",
    "University of Sioux Falls": "Cougars",
    "University of South Alabama": "Jaguars",
    "University of South Carolina": "Gamecocks",
    "University of South Carolina Upstate": "Spartans",
    "University of South Dakota": "Coyotes",
    "University of South Florida": "Bulls",
    "University of Southern California": "Trojans",
    "University of Southern Indiana": "Screaming Eagles",
    "University of Southern Maine": "Huskies",
    "University of Southern Mississippi": "Golden Eagles",
    "University of St. Francis": "Saints",
    "University of St. Thomas": "Tommies",
    "University of Tampa": "Spartans",
    "University of Tennessee": "Lady Volunteers",
    "University of Tennessee at Chattanooga": "Mocs",
    "University of Tennessee at Martin": "Skyhawks",
    "University of Texas": "Longhorns",
    "University of Texas at Arlington": "Mavericks",
    "University of Texas at El Paso": "Miners",
    "University of Texas at San Antonio": "Roadrunners",
    "University of Texas Rio Grande Valley": "Vaqueros",
    "University of the Incarnate Word": "Cardinals",
    "University of Toledo": "Rockets",
    "University of Tulsa": "Golden Hurricane",
    "University of Utah": "Utes",
    "University of Vermont": "Catamounts",
    "University of Virginia": "Cavaliers",
    "University of Washington": "Huskies",
    "University of West Alabama": "Tigers",
    "University of West Florida": "Argonauts",
    "University of West Georgia": "Wolves",
    "University of Wisconsin": "Badgers",
    "University of Wisconsin-Eau Claire": "Blugolds",
    "University of Wisconsin-Green Bay": "Phoenix",
    "University of Wisconsin-La Crosse": "Eagles",
    "University of Wisconsin-Milwaukee": "Panthers",
    "University of Wisconsin-Oshkosh": "Titans",
    "University of Wisconsin-Parkside": "Rangers",
    "University of Wisconsin-Platteville": "Pioneers",
    "University of Wisconsin-River Falls": "Falcons",
    "University of Wisconsin-Stevens Point": "Pointers",
    "University of Wisconsin-Stout": "Blue Devils",
    "University of Wisconsin-Superior": "Yellowjackets",
    "University of Wisconsin-Whitewater": "Warhawks",
    "University of Wyoming": "Cowgirls",
    "Upper Iowa University": "Peacocks",
    "Ursinus College": "Bears",
    "Ursuline College": "Arrows",
    "Utah State University": "Aggies",
    "Utah Tech University": "Trailblazers",
    "Utah Valley University": "Wolverines",
    "Utica University": "Pioneers",
    "Valdosta State University": "Blazers",
    "Valley City State University": "Vikings",
    "Valparaiso University": "Beacons",
    "Vanderbilt University": "Commodores",
    "Vassar College": "Brewers",
    "Villanova University": "Wildcats",
    "Virginia Commonwealth University": "Rams",
    "Virginia Military Institute": "Keydets",
    "Virginia State University": "Trojans",
    "Virginia Tech": "Hokies",
    "Virginia Union University": "Panthers",
    "Virginia Wesleyan University": "Marlins",
    "Viterbo University": "V-Hawks",
    "Wabash College": "Little Giants",
    "Wagner College": "Seahawks",
    "Wake Forest University": "Demon Deacons",
    "Walla Walla University": "Wolves",
    "Walsh University": "Cavaliers",
    "Warner Pacific University": "Knights",
    "Wartburg College": "Knights",
    "Washburn University": "Ichabods",
    "Washington & Jefferson College": "Presidents",
    "Washington & Lee University": "Generals",
    "Washington College": "Shoremen",
    "Washington State University": "Cougars",
    "Washington University in St. Louis": "Bears",
    "Wayland Baptist University": "Flying Queens",
    "Wayne State College": "Wildcats",
    "Wayne State University": "Warriors",
    "Weber State University": "Wildcats",
    "Webster University": "Gorloks",
    "Wellesley College": "Blue",
    "Wentworth Institute of Technology": "Leopards",
    "Wesleyan College": "Wolves",
    "Wesleyan University": "Cardinals",
    "West Chester University": "Golden Rams",
    "West Liberty University": "Hilltoppers",
    "West Texas A&M University": "Lady Buffs",
    "West Virginia State University": "Yellow Jackets",
    "West Virginia University": "Mountaineers",
    "West Virginia Wesleyan College": "Bobcats",
    "Western Carolina University": "Catamounts",
    "Western Connecticut State University": "Colonials",
    "Western Illinois University": "Leathernecks",
    "Western Kentucky University": "Hilltoppers",
    "Western Michigan University": "Broncos",
    "Western New England University": "Golden Bears",
    "Western Oregon University": "Wolves",
    "Western Washington University": "Vikings",
    "Westfield State University": "Owls",
    "Westminster College": "Titans",
    "Westmont College": "Warriors",
    "Wheaton College (IL)": "Thunder",
    "Wheaton College (MA)": "Lyons",
    "Wheeling University": "Cardinals",
    "Whitman College": "Blues",
    "Whittier College": "Poets",
    "Whitworth University": "Pirates",
    "Wichita State University": "Shockers",
    "Widener University": "Pride",
    "Wilkes University": "Colonels",
    "Willamette University": "Bearcats",
    "William & Mary": "Tribe",
    "William Jewell College": "Cardinals",
    "William Paterson University": "Pioneers",
    "William Peace University": "Pacers",
    "William Penn University": "Statesmen",
    "Williams College": "Ephs",
    "Wilmington College": "Quakers",
    "Wilmington University": "Wildcats",
    "Wilson College": "Phoenix",
    "Wingate University": "Bulldogs",
    "Winona State University": "Warriors",
    "Winston-Salem State University": "Rams",
    "Winthrop University": "Eagles",
    "Wittenberg University": "Tigers",
    "Wofford College": "Terriers",
    "Worcester Polytechnic Institute": "Engineers",
    "Worcester State University": "Lancers",
    "Wright State University": "Raiders",
    "Xavier University": "Musketeers",
    "Yale University": "Bulldogs",
    "York College of Pennsylvania": "Spartans",
    "Youngstown State University": "Penguins",
}


# ── Website URL generation ──
def generate_website(name):
    """Generate athletics website URL from university name."""
    # Common patterns for athletics sites
    KNOWN_WEBSITES = {
        "Stanford University": "https://gostanford.com/sports/womens-volleyball",
        "UCLA": "https://uclabruins.com/sports/womens-volleyball",
        "University of Nebraska": "https://huskers.com/sports/womens-volleyball",
        "University of Wisconsin": "https://uwbadgers.com/sports/womens-volleyball",
        "University of Texas": "https://texassports.com/sports/womens-volleyball",
        "University of Minnesota": "https://gophersports.com/sports/womens-volleyball",
        "Penn State University": "https://gopsusports.com/sports/womens-volleyball",
        "University of Pittsburgh": "https://pittsburghpanthers.com/sports/womens-volleyball",
        "University of Kentucky": "https://ukathletics.com/sports/womens-volleyball",
        "University of Florida": "https://floridagators.com/sports/womens-volleyball",
        "University of Washington": "https://gohuskies.com/sports/womens-volleyball",
        "University of Oregon": "https://goducks.com/sports/womens-volleyball",
        "Ohio State University": "https://ohiostatebuckeyes.com/sports/womens-volleyball",
        "Purdue University": "https://purduesports.com/sports/womens-volleyball",
        "University of Michigan": "https://mgoblue.com/sports/womens-volleyball",
        "Baylor University": "https://baylorbears.com/sports/womens-volleyball",
        "Creighton University": "https://gocreighton.com/sports/womens-volleyball",
        "University of Louisville": "https://gocards.com/sports/womens-volleyball",
        "University of Southern California": "https://usctrojans.com/sports/womens-volleyball",
        "University of Hawaii": "https://hawaiiathletics.com/sports/womens-volleyball",
        "Brigham Young University": "https://byucougars.com/sports/womens-volleyball",
        "University of Colorado Boulder": "https://cubuffs.com/sports/womens-volleyball",
        "University of Arizona": "https://arizonawildcats.com/sports/womens-volleyball",
        "Duke University": "https://goduke.com/sports/womens-volleyball",
        "University of Notre Dame": "https://und.com/sports/womens-volleyball",
        "Marquette University": "https://gomarquette.com/sports/womens-volleyball",
        "Rice University": "https://riceowls.com/sports/womens-volleyball",
        "Pepperdine University": "https://pepperdinewaves.com/sports/womens-volleyball",
        "University of San Diego": "https://usdtoreros.com/sports/womens-volleyball",
        "Gonzaga University": "https://gozags.com/sports/womens-volleyball",
        "University of Kansas": "https://kuathletics.com/sports/womens-volleyball",
        "Iowa State University": "https://cyclones.com/sports/womens-volleyball",
        "Kansas State University": "https://kstatesports.com/sports/womens-volleyball",
        "Texas Christian University": "https://gofrogs.com/sports/womens-volleyball",
        "West Virginia University": "https://wvusports.com/sports/womens-volleyball",
        "Oklahoma State University": "https://okstate.com/sports/womens-volleyball",
        "University of Oklahoma": "https://soonersports.com/sports/womens-volleyball",
        "Texas Tech University": "https://texastech.com/sports/womens-volleyball",
        "University of Iowa": "https://hawkeyesports.com/sports/womens-volleyball",
        "University of Georgia": "https://georgiadogs.com/sports/womens-volleyball",
        "University of South Carolina": "https://gamecocksonline.com/sports/womens-volleyball",
        "University of Tennessee": "https://utsports.com/sports/womens-volleyball",
        "University of Alabama": "https://rolltide.com/sports/womens-volleyball",
        "Auburn University": "https://auburntigers.com/sports/womens-volleyball",
        "Mississippi State University": "https://hailstate.com/sports/womens-volleyball",
        "University of Mississippi": "https://olemisssports.com/sports/womens-volleyball",
        "University of Missouri": "https://mutigers.com/sports/womens-volleyball",
        "Vanderbilt University": "https://vucommodores.com/sports/womens-volleyball",
        "Louisiana State University": "https://lsusports.net/sports/womens-volleyball",
        "Texas A&M University": "https://12thman.com/sports/womens-volleyball",
        "Florida State University": "https://seminoles.com/sports/womens-volleyball",
        "Clemson University": "https://clemsontigers.com/sports/womens-volleyball",
        "Virginia Tech": "https://hokiesports.com/sports/womens-volleyball",
        "University of Virginia": "https://virginiasports.com/sports/womens-volleyball",
        "University of North Carolina": "https://goheels.com/sports/womens-volleyball",
        "North Carolina State University": "https://gopack.com/sports/womens-volleyball",
        "Wake Forest University": "https://godeacs.com/sports/womens-volleyball",
        "Syracuse University": "https://cuse.com/sports/womens-volleyball",
        "Boston College": "https://bceagles.com/sports/womens-volleyball",
        "University of Miami": "https://miamihurricanes.com/sports/womens-volleyball",
        "Michigan State University": "https://msuspartans.com/sports/womens-volleyball",
        "Indiana University": "https://iuhoosiers.com/sports/womens-volleyball",
        "Northwestern University": "https://nusports.com/sports/womens-volleyball",
        "University of Illinois": "https://fightingillini.com/sports/womens-volleyball",
        "Rutgers University": "https://scarletknights.com/sports/womens-volleyball",
        "University of Maryland": "https://umterps.com/sports/womens-volleyball",
    }
    return KNOWN_WEBSITES.get(name, "")


async def enrich():
    """Enrich all universities in the knowledge base."""
    universities = await db.university_knowledge_base.find({}, {"_id": 0}).to_list(2000)
    print(f"Found {len(universities)} universities to enrich")

    updated = 0
    for uni in universities:
        name = uni.get("university_name", "")
        if not name:
            continue

        updates = {}

        # Mascot
        if not uni.get("mascot") and name in MASCOTS:
            updates["mascot"] = MASCOTS[name]

        # Website
        if not uni.get("website"):
            website = generate_website(name)
            if website:
                updates["website"] = website

        # Scholarship type based on division
        if not uni.get("scholarship_type"):
            div = uni.get("division", "")
            if div == "D1":
                updates["scholarship_type"] = "Full & Partial Athletic"
            elif div == "D2":
                updates["scholarship_type"] = "Partial Athletic"
            elif div == "D3":
                updates["scholarship_type"] = "Academic & Merit Only"

        if updates:
            await db.university_knowledge_base.update_one(
                {"university_name": name},
                {"$set": updates}
            )
            updated += 1

    print(f"Updated {updated} universities")

    # Summary
    total = await db.university_knowledge_base.count_documents({})
    with_mascot = await db.university_knowledge_base.count_documents({"mascot": {"$ne": ""}})
    with_website = await db.university_knowledge_base.count_documents({"website": {"$ne": ""}})
    with_coach = await db.university_knowledge_base.count_documents({"primary_coach": {"$ne": ""}})
    with_scholarship = await db.university_knowledge_base.count_documents({"scholarship_type": {"$ne": ""}})

    print(f"\n--- Enrichment Summary ---")
    print(f"Total universities: {total}")
    print(f"With mascot: {with_mascot}/{total} ({with_mascot*100//total}%)")
    print(f"With website: {with_website}/{total} ({with_website*100//total}%)")
    print(f"With coach: {with_coach}/{total} ({with_coach*100//total}%)")
    print(f"With scholarship type: {with_scholarship}/{total} ({with_scholarship*100//total}%)")


if __name__ == "__main__":
    asyncio.run(enrich())
