"""Seed the university_knowledge_base collection with volleyball program data.

Run once to populate, or re-run to refresh (idempotent via domain key).
Designed so a weekly job can call seed_kb() to upsert updated data.
"""

import asyncio
from datetime import datetime, timezone


VOLLEYBALL_PROGRAMS = [
    {
        "domain": "stanford.edu",
        "university_name": "Stanford University",
        "mascot": "Cardinal",
        "division": "D1",
        "conference": "Pac-12",
        "state": "CA",
        "city": "Stanford",
        "region": "West",
        "website": "https://gostanford.com/sports/womens-volleyball",
        "enrollment": 17680,
        "tuition_in_state": 58416,
        "tuition_out_state": 58416,
        "acceptance_rate": 4,
        "avg_gpa": 3.96,
        "colors": ["#8C1515", "#FFFFFF"],
        "coaching_staff": [
            {"name": "Kevin Hambly", "role": "Head Coach", "email": "khambly@stanford.edu"},
            {"name": "Jillian Goodman", "role": "Associate Head Coach", "email": "jgoodman@stanford.edu"},
        ],
        "program_stats": {
            "national_championships": 9,
            "conference_titles": 19,
            "ncaa_appearances": 36,
            "rpi_ranking": 3,
            "win_loss_record": "28-4",
            "home_record": "15-0",
        },
        "facilities": "Maples Pavilion (7,391 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 20,
        "description": "Stanford Women's Volleyball is one of the most decorated programs in NCAA history with 9 national championships. Known for academic excellence and athletic achievement.",
    },
    {
        "domain": "unl.edu",
        "university_name": "University of Nebraska",
        "mascot": "Cornhuskers",
        "division": "D1",
        "conference": "Big Ten",
        "state": "NE",
        "city": "Lincoln",
        "region": "Midwest",
        "website": "https://huskers.com/sports/volleyball",
        "enrollment": 24431,
        "tuition_in_state": 10458,
        "tuition_out_state": 27468,
        "acceptance_rate": 63,
        "avg_gpa": 3.55,
        "colors": ["#D00000", "#FFFFFF"],
        "coaching_staff": [
            {"name": "John Cook", "role": "Head Coach", "email": "jcook@unl.edu"},
            {"name": "Tyler Hildebrand", "role": "Associate Head Coach", "email": "thildebrand@unl.edu"},
        ],
        "program_stats": {
            "national_championships": 5,
            "conference_titles": 10,
            "ncaa_appearances": 32,
            "rpi_ranking": 5,
            "win_loss_record": "30-3",
            "home_record": "17-0",
        },
        "facilities": "Bob Devaney Sports Center (8,000 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full",
        "roster_size": 18,
        "description": "Nebraska volleyball is a cultural institution. The Cornhuskers regularly set attendance records and have one of the most passionate fan bases in all of college sports.",
    },
    {
        "domain": "wisc.edu",
        "university_name": "University of Wisconsin",
        "mascot": "Badgers",
        "division": "D1",
        "conference": "Big Ten",
        "state": "WI",
        "city": "Madison",
        "region": "Midwest",
        "website": "https://uwbadgers.com/sports/volleyball",
        "enrollment": 47932,
        "tuition_in_state": 10796,
        "tuition_out_state": 39427,
        "acceptance_rate": 49,
        "avg_gpa": 3.85,
        "colors": ["#C5050C", "#FFFFFF"],
        "coaching_staff": [
            {"name": "Kelly Sheffield", "role": "Head Coach", "email": "ksheffield@wisc.edu"},
            {"name": "Brittany Dildine", "role": "Associate Head Coach", "email": "bdildine@wisc.edu"},
        ],
        "program_stats": {
            "national_championships": 1,
            "conference_titles": 5,
            "ncaa_appearances": 20,
            "rpi_ranking": 2,
            "win_loss_record": "31-2",
            "home_record": "16-0",
        },
        "facilities": "UW Field House (10,000+ capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 19,
        "description": "The 2021 NCAA champions, Wisconsin volleyball has become a consistent powerhouse under Coach Sheffield, combining elite play with one of the top academic institutions in the country.",
    },
    {
        "domain": "utexas.edu",
        "university_name": "University of Texas",
        "mascot": "Longhorns",
        "division": "D1",
        "conference": "SEC",
        "state": "TX",
        "city": "Austin",
        "region": "South",
        "website": "https://texassports.com/sports/volleyball",
        "enrollment": 51832,
        "tuition_in_state": 11448,
        "tuition_out_state": 40996,
        "acceptance_rate": 31,
        "avg_gpa": 3.80,
        "colors": ["#BF5700", "#FFFFFF"],
        "coaching_staff": [
            {"name": "Jerritt Elliott", "role": "Head Coach", "email": "jelliott@utexas.edu"},
            {"name": "Tonya Johnson", "role": "Associate Head Coach", "email": "tjohnson@utexas.edu"},
        ],
        "program_stats": {
            "national_championships": 3,
            "conference_titles": 12,
            "ncaa_appearances": 28,
            "rpi_ranking": 1,
            "win_loss_record": "27-5",
            "home_record": "14-1",
        },
        "facilities": "Gregory Gymnasium (4,400 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full",
        "roster_size": 17,
        "description": "Texas volleyball is a perennial national title contender with 3 championships. The Longhorns play in one of the most electric atmospheres in college volleyball.",
    },
    {
        "domain": "pitt.edu",
        "university_name": "University of Pittsburgh",
        "mascot": "Panthers",
        "division": "D1",
        "conference": "ACC",
        "state": "PA",
        "city": "Pittsburgh",
        "region": "East",
        "website": "https://pittsburghpanthers.com/sports/volleyball",
        "enrollment": 34934,
        "tuition_in_state": 20220,
        "tuition_out_state": 36564,
        "acceptance_rate": 42,
        "avg_gpa": 3.75,
        "colors": ["#003594", "#FFB81C"],
        "coaching_staff": [
            {"name": "Dan Fisher", "role": "Head Coach", "email": "dfisher@pitt.edu"},
            {"name": "Emily Hartong", "role": "Assistant Coach", "email": "ehartong@pitt.edu"},
        ],
        "program_stats": {
            "national_championships": 1,
            "conference_titles": 8,
            "ncaa_appearances": 17,
            "rpi_ranking": 4,
            "win_loss_record": "32-2",
            "home_record": "16-0",
        },
        "facilities": "Fitzgerald Field House (5,500 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 17,
        "description": "Pitt won its first national championship in 2022 and has rapidly become an elite program under Coach Fisher, known for a strong blocking and defensive style.",
    },
    {
        "domain": "louisville.edu",
        "university_name": "University of Louisville",
        "mascot": "Cardinals",
        "division": "D1",
        "conference": "ACC",
        "state": "KY",
        "city": "Louisville",
        "region": "South",
        "website": "https://gocards.com/sports/volleyball",
        "enrollment": 22293,
        "tuition_in_state": 12324,
        "tuition_out_state": 29340,
        "acceptance_rate": 68,
        "avg_gpa": 3.50,
        "colors": ["#AD0000", "#000000"],
        "coaching_staff": [
            {"name": "Dani Busboom Kelly", "role": "Head Coach", "email": "dbkelly@louisville.edu"},
            {"name": "Joe Legge", "role": "Assistant Coach", "email": "jlegge@louisville.edu"},
        ],
        "program_stats": {
            "national_championships": 1,
            "conference_titles": 6,
            "ncaa_appearances": 15,
            "rpi_ranking": 7,
            "win_loss_record": "31-4",
            "home_record": "15-1",
        },
        "facilities": "L&N Federal Credit Union Arena (2,017 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 18,
        "description": "Louisville has emerged as a national power, winning the 2024 national title. Coach Busboom Kelly is a former All-American who has built a championship culture.",
    },
    {
        "domain": "usc.edu",
        "university_name": "University of Southern California",
        "mascot": "Trojans",
        "division": "D1",
        "conference": "Big Ten",
        "state": "CA",
        "city": "Los Angeles",
        "region": "West",
        "website": "https://usctrojans.com/sports/volleyball",
        "enrollment": 49500,
        "tuition_in_state": 63468,
        "tuition_out_state": 63468,
        "acceptance_rate": 12,
        "avg_gpa": 3.88,
        "colors": ["#990000", "#FFC72C"],
        "coaching_staff": [
            {"name": "Brad Keller", "role": "Head Coach", "email": "bkeller@usc.edu"},
            {"name": "Kendra Potts", "role": "Associate Head Coach", "email": "kpotts@usc.edu"},
        ],
        "program_stats": {
            "national_championships": 6,
            "conference_titles": 15,
            "ncaa_appearances": 31,
            "rpi_ranking": 6,
            "win_loss_record": "26-7",
            "home_record": "13-2",
        },
        "facilities": "Galen Center (10,258 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full",
        "roster_size": 19,
        "description": "USC has won 6 national titles and is one of the most storied volleyball programs. Based in LA, it offers unmatched recruiting and campus life.",
    },
    {
        "domain": "umn.edu",
        "university_name": "University of Minnesota",
        "mascot": "Golden Gophers",
        "division": "D1",
        "conference": "Big Ten",
        "state": "MN",
        "city": "Minneapolis",
        "region": "Midwest",
        "website": "https://gophersports.com/sports/volleyball",
        "enrollment": 52376,
        "tuition_in_state": 15472,
        "tuition_out_state": 35238,
        "acceptance_rate": 73,
        "avg_gpa": 3.60,
        "colors": ["#7A0019", "#FFCC33"],
        "coaching_staff": [
            {"name": "Keegan Cook", "role": "Head Coach", "email": "kcook@umn.edu"},
            {"name": "Alex Magers", "role": "Assistant Coach", "email": "amagers@umn.edu"},
        ],
        "program_stats": {
            "national_championships": 0,
            "conference_titles": 3,
            "ncaa_appearances": 22,
            "rpi_ranking": 8,
            "win_loss_record": "27-6",
            "home_record": "14-1",
        },
        "facilities": "Maturi Pavilion (5,700 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 18,
        "description": "Minnesota volleyball consistently ranks in the top 10 nationally and competes in the powerhouse Big Ten conference. Strong support and facilities.",
    },
    {
        "domain": "byu.edu",
        "university_name": "Brigham Young University",
        "mascot": "Cougars",
        "division": "D1",
        "conference": "Big 12",
        "state": "UT",
        "city": "Provo",
        "region": "West",
        "website": "https://byucougars.com/sports/volleyball",
        "enrollment": 34799,
        "tuition_in_state": 6304,
        "tuition_out_state": 12608,
        "acceptance_rate": 59,
        "avg_gpa": 3.73,
        "colors": ["#002E5D", "#FFFFFF"],
        "coaching_staff": [
            {"name": "Heather Olmstead", "role": "Head Coach", "email": "holmstead@byu.edu"},
            {"name": "Mark Francis", "role": "Associate Head Coach", "email": "mfrancis@byu.edu"},
        ],
        "program_stats": {
            "national_championships": 0,
            "conference_titles": 7,
            "ncaa_appearances": 23,
            "rpi_ranking": 10,
            "win_loss_record": "28-3",
            "home_record": "15-0",
        },
        "facilities": "Smith Fieldhouse (5,000 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 18,
        "description": "BYU is one of the most affordable programs at the D1 level and has a storied tradition in volleyball. The Cougars are perennial top-15 contenders.",
    },
    {
        "domain": "uw.edu",
        "university_name": "University of Washington",
        "mascot": "Huskies",
        "division": "D1",
        "conference": "Big Ten",
        "state": "WA",
        "city": "Seattle",
        "region": "West",
        "website": "https://gohuskies.com/sports/volleyball",
        "enrollment": 47400,
        "tuition_in_state": 12076,
        "tuition_out_state": 39906,
        "acceptance_rate": 48,
        "avg_gpa": 3.72,
        "colors": ["#4B2E83", "#B7A57A"],
        "coaching_staff": [
            {"name": "Keegan Cook", "role": "Head Coach", "email": "kcook@uw.edu"},
        ],
        "program_stats": {
            "national_championships": 1,
            "conference_titles": 4,
            "ncaa_appearances": 19,
            "rpi_ranking": 9,
            "win_loss_record": "27-4",
            "home_record": "14-0",
        },
        "facilities": "Alaska Airlines Arena (10,000 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 18,
        "description": "Washington won the 2005 national championship and is a consistent Pac-12 contender. Located in Seattle, it offers a great blend of athletics and academics.",
    },
    # ── D2 Programs ──
    {
        "domain": "tamuk.edu",
        "university_name": "Texas A&M University-Kingsville",
        "mascot": "Javelinas",
        "division": "D2",
        "conference": "Lone Star Conference",
        "state": "TX",
        "city": "Kingsville",
        "region": "South",
        "website": "https://javelinaathletics.com/sports/volleyball",
        "enrollment": 7500,
        "tuition_in_state": 8892,
        "tuition_out_state": 19572,
        "acceptance_rate": 79,
        "avg_gpa": 3.20,
        "colors": ["#003DA5", "#FFB81C"],
        "coaching_staff": [
            {"name": "Tanya Allen", "role": "Head Coach", "email": "tallen@tamuk.edu"},
        ],
        "program_stats": {
            "national_championships": 0,
            "conference_titles": 4,
            "ncaa_appearances": 8,
            "rpi_ranking": None,
            "win_loss_record": "22-8",
            "home_record": "11-3",
        },
        "facilities": "Steinke Center",
        "athletic_scholarships": True,
        "scholarship_type": "Partial",
        "roster_size": 16,
        "description": "TAMUK competes in the Lone Star Conference and offers strong D2 volleyball with partial scholarships available.",
    },
    {
        "domain": "concordia-stp.edu",
        "university_name": "Concordia University, St. Paul",
        "mascot": "Golden Bears",
        "division": "D2",
        "conference": "NSIC",
        "state": "MN",
        "city": "St. Paul",
        "region": "Midwest",
        "website": "https://cubearsports.com/sports/volleyball",
        "enrollment": 5200,
        "tuition_in_state": 23750,
        "tuition_out_state": 23750,
        "acceptance_rate": 65,
        "avg_gpa": 3.30,
        "colors": ["#002D72", "#C8A74E"],
        "coaching_staff": [
            {"name": "Brady Starkey", "role": "Head Coach", "email": "bstarkey@concordia.edu"},
        ],
        "program_stats": {
            "national_championships": 8,
            "conference_titles": 14,
            "ncaa_appearances": 16,
            "rpi_ranking": None,
            "win_loss_record": "33-1",
            "home_record": "16-0",
        },
        "facilities": "Gangelhoff Center (2,600 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Partial",
        "roster_size": 18,
        "description": "Concordia-St. Paul is a D2 dynasty with 8 national championships, dominating the NSIC. One of the most successful programs at any division level.",
    },
    {
        "domain": "wingate.edu",
        "university_name": "Wingate University",
        "mascot": "Bulldogs",
        "division": "D2",
        "conference": "South Atlantic Conference",
        "state": "NC",
        "city": "Wingate",
        "region": "East",
        "website": "https://wingatebulldogs.com/sports/volleyball",
        "enrollment": 3800,
        "tuition_in_state": 38270,
        "tuition_out_state": 38270,
        "acceptance_rate": 72,
        "avg_gpa": 3.40,
        "colors": ["#002855", "#B69E55"],
        "coaching_staff": [
            {"name": "Rachel Calvert", "role": "Head Coach", "email": "rcalvert@wingate.edu"},
        ],
        "program_stats": {
            "national_championships": 0,
            "conference_titles": 3,
            "ncaa_appearances": 5,
            "rpi_ranking": None,
            "win_loss_record": "25-6",
            "home_record": "12-2",
        },
        "facilities": "Cuddy Arena",
        "athletic_scholarships": True,
        "scholarship_type": "Partial",
        "roster_size": 16,
        "description": "Wingate competes in the SAC and has been a rising D2 program with strong regional recruiting and a growing tradition.",
    },
    # ── D3 Programs ──
    {
        "domain": "callutheran.edu",
        "university_name": "California Lutheran University",
        "mascot": "Regals",
        "division": "D3",
        "conference": "SCIAC",
        "state": "CA",
        "city": "Thousand Oaks",
        "region": "West",
        "website": "https://clusports.com/sports/volleyball",
        "enrollment": 4200,
        "tuition_in_state": 48040,
        "tuition_out_state": 48040,
        "acceptance_rate": 56,
        "avg_gpa": 3.55,
        "colors": ["#4B2582", "#FFD100"],
        "coaching_staff": [
            {"name": "Kellee Roesel", "role": "Head Coach", "email": "kroesel@callutheran.edu"},
        ],
        "program_stats": {
            "national_championships": 3,
            "conference_titles": 20,
            "ncaa_appearances": 24,
            "rpi_ranking": None,
            "win_loss_record": "30-4",
            "home_record": "14-1",
        },
        "facilities": "Gilbert Sports & Fitness Center",
        "athletic_scholarships": False,
        "scholarship_type": "Academic/Merit Only",
        "roster_size": 22,
        "description": "Cal Lutheran is a D3 powerhouse with 3 national titles, competing in the SCIAC. No athletic scholarships, but strong academic merit aid.",
    },
    {
        "domain": "emory.edu",
        "university_name": "Emory University",
        "mascot": "Eagles",
        "division": "D3",
        "conference": "UAA",
        "state": "GA",
        "city": "Atlanta",
        "region": "South",
        "website": "https://emoryathletics.com/sports/volleyball",
        "enrollment": 15252,
        "tuition_in_state": 57948,
        "tuition_out_state": 57948,
        "acceptance_rate": 11,
        "avg_gpa": 3.92,
        "colors": ["#012169", "#B3A369"],
        "coaching_staff": [
            {"name": "Jenny McDowell", "role": "Head Coach", "email": "jmcdowell@emory.edu"},
        ],
        "program_stats": {
            "national_championships": 5,
            "conference_titles": 12,
            "ncaa_appearances": 20,
            "rpi_ranking": None,
            "win_loss_record": "31-3",
            "home_record": "15-0",
        },
        "facilities": "Woodruff P.E. Center",
        "athletic_scholarships": False,
        "scholarship_type": "Academic/Need-Based Only",
        "roster_size": 20,
        "description": "Emory is an academic and D3 volleyball powerhouse with 5 national championships. Offers top-tier education paired with elite volleyball.",
    },
    {
        "domain": "claremont.edu",
        "university_name": "Claremont-Mudd-Scripps",
        "mascot": "Stags/Athenas",
        "division": "D3",
        "conference": "SCIAC",
        "state": "CA",
        "city": "Claremont",
        "region": "West",
        "website": "https://cmsathletics.com/sports/volleyball",
        "enrollment": 5400,
        "tuition_in_state": 60907,
        "tuition_out_state": 60907,
        "acceptance_rate": 10,
        "avg_gpa": 3.95,
        "colors": ["#800000", "#FFD700"],
        "coaching_staff": [
            {"name": "Annette Fotopoulos", "role": "Head Coach", "email": "afotopoulos@cmc.edu"},
        ],
        "program_stats": {
            "national_championships": 0,
            "conference_titles": 6,
            "ncaa_appearances": 12,
            "rpi_ranking": None,
            "win_loss_record": "24-6",
            "home_record": "12-1",
        },
        "facilities": "Roberts Pavilion",
        "athletic_scholarships": False,
        "scholarship_type": "Academic/Need-Based Only",
        "roster_size": 20,
        "description": "Claremont-Mudd-Scripps combines world-class academics (Claremont consortium) with strong D3 athletics in the SCIAC.",
    },
    # ── More D1 Programs ──
    {
        "domain": "osu.edu",
        "university_name": "Ohio State University",
        "mascot": "Buckeyes",
        "division": "D1",
        "conference": "Big Ten",
        "state": "OH",
        "city": "Columbus",
        "region": "Midwest",
        "website": "https://ohiostatebuckeyes.com/sports/volleyball",
        "enrollment": 61369,
        "tuition_in_state": 11936,
        "tuition_out_state": 35019,
        "acceptance_rate": 53,
        "avg_gpa": 3.70,
        "colors": ["#BB0000", "#666666"],
        "coaching_staff": [
            {"name": "Jen Flynn Oldenburg", "role": "Head Coach", "email": "joldenburg@osu.edu"},
        ],
        "program_stats": {
            "national_championships": 0,
            "conference_titles": 2,
            "ncaa_appearances": 18,
            "rpi_ranking": 11,
            "win_loss_record": "25-7",
            "home_record": "13-1",
        },
        "facilities": "Covelli Center (3,854 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 18,
        "description": "Ohio State plays in the demanding Big Ten and has top-tier facilities. Strong program with growing momentum.",
    },
    {
        "domain": "ufl.edu",
        "university_name": "University of Florida",
        "mascot": "Gators",
        "division": "D1",
        "conference": "SEC",
        "state": "FL",
        "city": "Gainesville",
        "region": "South",
        "website": "https://floridagators.com/sports/volleyball",
        "enrollment": 55781,
        "tuition_in_state": 6380,
        "tuition_out_state": 28658,
        "acceptance_rate": 23,
        "avg_gpa": 3.80,
        "colors": ["#0021A5", "#FA4616"],
        "coaching_staff": [
            {"name": "Mary Wise", "role": "Head Coach", "email": "mwise@ufl.edu"},
        ],
        "program_stats": {
            "national_championships": 3,
            "conference_titles": 22,
            "ncaa_appearances": 33,
            "rpi_ranking": 12,
            "win_loss_record": "26-5",
            "home_record": "14-0",
        },
        "facilities": "Exactech Arena (10,133 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full",
        "roster_size": 17,
        "description": "Florida is a volleyball powerhouse with 3 national championships and the SEC's most decorated program under legendary coach Mary Wise.",
    },
    {
        "domain": "psu.edu",
        "university_name": "Penn State University",
        "mascot": "Nittany Lions",
        "division": "D1",
        "conference": "Big Ten",
        "state": "PA",
        "city": "University Park",
        "region": "East",
        "website": "https://gopsusports.com/sports/volleyball",
        "enrollment": 47261,
        "tuition_in_state": 19286,
        "tuition_out_state": 37468,
        "acceptance_rate": 55,
        "avg_gpa": 3.60,
        "colors": ["#041E42", "#FFFFFF"],
        "coaching_staff": [
            {"name": "Katie Schumacher-Cawley", "role": "Head Coach", "email": "kcawley@psu.edu"},
        ],
        "program_stats": {
            "national_championships": 7,
            "conference_titles": 15,
            "ncaa_appearances": 38,
            "rpi_ranking": 14,
            "win_loss_record": "24-8",
            "home_record": "12-2",
        },
        "facilities": "Rec Hall (6,023 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 19,
        "description": "Penn State is tied for the most NCAA volleyball championships (7) and has one of the richest traditions in the sport. Known for intense home atmosphere at Rec Hall.",
    },
    {
        "domain": "creighton.edu",
        "university_name": "Creighton University",
        "mascot": "Bluejays",
        "division": "D1",
        "conference": "Big East",
        "state": "NE",
        "city": "Omaha",
        "region": "Midwest",
        "website": "https://gocreighton.com/sports/volleyball",
        "enrollment": 8782,
        "tuition_in_state": 44580,
        "tuition_out_state": 44580,
        "acceptance_rate": 72,
        "avg_gpa": 3.65,
        "colors": ["#005CA9", "#FFFFFF"],
        "coaching_staff": [
            {"name": "Kirsten Bernthal Booth", "role": "Head Coach", "email": "kbooth@creighton.edu"},
        ],
        "program_stats": {
            "national_championships": 0,
            "conference_titles": 12,
            "ncaa_appearances": 14,
            "rpi_ranking": 13,
            "win_loss_record": "30-3",
            "home_record": "16-0",
        },
        "facilities": "D.J. Sokol Arena (2,500 capacity)",
        "athletic_scholarships": True,
        "scholarship_type": "Full + Partial",
        "roster_size": 17,
        "description": "Creighton is the dominant force in the Big East with 12 conference titles. A smaller, private university that punches well above its weight in volleyball.",
    },
    # ── NAIA Program ──
    {
        "domain": "park.edu",
        "university_name": "Park University",
        "mascot": "Pirates",
        "division": "NAIA",
        "conference": "AMC",
        "state": "MO",
        "city": "Parkville",
        "region": "Midwest",
        "website": "https://parkathletics.com/sports/volleyball",
        "enrollment": 8200,
        "tuition_in_state": 13350,
        "tuition_out_state": 13350,
        "acceptance_rate": 70,
        "avg_gpa": 3.10,
        "colors": ["#002855", "#FFD100"],
        "coaching_staff": [
            {"name": "Ashley Meyer", "role": "Head Coach", "email": "ameyer@park.edu"},
        ],
        "program_stats": {
            "national_championships": 0,
            "conference_titles": 2,
            "ncaa_appearances": 0,
            "rpi_ranking": None,
            "win_loss_record": "20-10",
            "home_record": "10-4",
        },
        "facilities": "Plaster Gymnasium",
        "athletic_scholarships": True,
        "scholarship_type": "Partial",
        "roster_size": 16,
        "description": "Park University is an NAIA program offering volleyball scholarships in a smaller, supportive environment with a focus on student-athlete development.",
    },
]

# Unique lists for filter dropdowns
ALL_DIVISIONS = sorted(set(p["division"] for p in VOLLEYBALL_PROGRAMS))
ALL_STATES = sorted(set(p["state"] for p in VOLLEYBALL_PROGRAMS))
ALL_CONFERENCES = sorted(set(p["conference"] for p in VOLLEYBALL_PROGRAMS))
ALL_REGIONS = sorted(set(p["region"] for p in VOLLEYBALL_PROGRAMS))


async def seed_kb(database):
    """Upsert all volleyball programs into university_knowledge_base."""
    collection = database.university_knowledge_base
    now = datetime.now(timezone.utc).isoformat()

    for program in VOLLEYBALL_PROGRAMS:
        program["updated_at"] = now
        await collection.update_one(
            {"domain": program["domain"]},
            {"$set": program, "$setOnInsert": {"created_at": now}},
            upsert=True,
        )

    # Create indexes for search performance
    await collection.create_index("domain", unique=True)
    await collection.create_index("university_name")
    await collection.create_index("division")
    await collection.create_index("state")
    await collection.create_index("conference")
    await collection.create_index("region")
    await collection.create_index([("university_name", "text")])

    count = await collection.count_documents({})
    return count
